### ISSUE TITLE
Problem with city

### ISSUE THREAD

**Issue by AMGSoUL** [struthio/phpOregonI600#10]
Hello! Thanks for your server. But i have a problem. Then im choose europe/russian/saratov im always got error. Forecat, weather map or yahoo always error.
![struthio](https://cloud.githubusercontent.com/assets/15894103/23329608/4c9ecee4-fb55-11e6-864e-a783e8dfc07c.PNG)
I try reinstall programm and visual c, but nothing help. But then a choose Poland, I did not get an error.
Any idea?
Sorry for my english, and thanks for help!

**Comment by struthio** [comment]
No I think in might be a problem with data provided by server. I had some Time Zone issues with Saratov already. I will try to look at it on weekend.

**Comment by AMGSoUL** [comment]
Ok, thanks a lot!

**Comment by struthio** [comment]
Hi.
I think You got this error because of some problems with Europe/Saratov timezone.
I changed time zone to Europe/Moscow for Saratov. Please check if error still appears.

**Comment by AMGSoUL** [comment]
It's working! Thanks a lot for your helping!

**Comment by AMGSoUL** [comment]
Hello, I have the same error again, can you help me?
Sorry for disturbing

**Comment by struthio** [comment]
Please give me following error:
1. Which country/region/city You are using (and which provider Yahoo / OPenWeatherMap / Forecast.io )?

**Comment by AMGSoUL** [comment]
Europe/Russia/Saratov Forecast.io

**Comment by struthio** [comment]
Does the error still occurs ? I see nothing strange with XML provided to Weather Station.

**Comment by AMGSoUL** [comment]
Yes, and i cant open http://oregon.superstar.one.pl/ (ERR_CONNECTION_TIMED_OUT)

**Comment by AMGSoUL** [comment]
Now site open and programm don't crash, thank you!
