### ISSUE TITLE
I ask to add the city

### ISSUE THREAD

**Issue by sanzav** [struthio/phpOregonI600#12]
so if you want to add your City, please register GitHub Issue with City details like Continent, Country, Cityname, Longitute, Latitude

Europe, Russia, Rostov-on-Don, Longitude: 39°43′23″ E, Latitude: 47°13′52″ N

Very much I thank.

**Comment by struthio** [comment]
Hello,
I'll try to add it within this week.

**Comment by sanzav** [comment]
Hello,
Whether you plan to change docker because yahoo closed service of weather ?

**Comment by struthio** [comment]
Please check if new city works correctly (I had some issue adding it).

As for docker I do not have plans to update it soon. Project structure was totally rebuild and that would require building new docker from scratch.

**Comment by sanzav** [comment]
On all 3 servers of weather does not work.
Saratov - work.
Very much I thank.

**Comment by sanzav** [comment]
Saratov -  does not work too.

**Comment by sanzav** [comment]
Weather appeared on (the 2nd point Europe) openwether, but it is not right.

**Comment by victorstar1** [comment]
Hello, can you add Europe, Ukraine, Vinnytsia (Vinnytsya), Vinnytsia Oblast, Longitute: 28.4809700°  Latitude: 49.2327800°
Regards

**Comment by sanzav** [comment]
Я не владею сервером Вам нужно написать struthio\
I do not own the server to you it is necessary to write struthio

**Comment by struthio** [comment]
Hi,

City added. Please verify.

**Comment by struthio** [comment]
Rostov-on-Don - Should also be fixed
