### ISSUE TITLE
Add new  city

### ISSUE THREAD

**Issue by victorstar1** [struthio/phpOregonI600#13]
Hello, can you add Europe, Ukraine, Vinnytsia (Vinnytsya), Vinnytsia Oblast, Longitute: 28.4809700° Latitude: 49.2327800°
Regards

**Comment by struthio** [comment]
Hi.

City Added. Please verify

**Comment by moviefuns** [comment]
Hi.
Would you please add below cities:
2@ASIA@2250@CHINA@3676@LIUSHA@23.29@116.17@2162118@Asia/Shanghai
2@ASIA@2250@CHINA@3676@JIEYANG@23.37@116.71@2161849@Asia/Shanghai
2@ASIA@2250@CHINA@3676@SHANTOU@23.37@116.71@2162312@Asia/Shanghai
2@ASIA@2250@CHINA@3686@SHENZHEN@22.55@114.1@20253976@Asia/Shanghai
2@ASIA@2250@CHINA@14130@ZHONGSHAN@38.9@121.67@2147350@Asia/Shanghai
2@ASIA@2250@CHINA@3673@GUANGZHOU@23.1666666666667@113.333333333333@22116557@Asia/Shanghai

Thanks for your codes! Great job!
