### ISSUE TITLE
linux sending forecast through 433 usb hub

### ISSUE THREAD

**Issue by moviefuns** [struthio/phpOregonI600#16]
Is that possible to send customized forecast data through the 433Mhz USB hub by some linux board, like raspberry pi?
If it's possible, we can setup a mini set automatically griping forecast and sending to the station.

**Comment by struthio** [comment]
It is all dependent on what You mean '433Mhz USB Hub'.
I guess it is possible but You would have to know protocol used for communication.
Protocol used to communicate between Server<->WeatherOS have nothing in-common with communication PC<->Device
