### ISSUE TITLE
Add new city please

### ISSUE THREAD

**Issue by AMGSoUL** [struthio/phpOregonI600#2]
Hello, can u pls add new city (woeid 2123272). And i can't find weather os v. 1.2 for windows 7 (i600). Do you have installer? Send me azgroove@gmail.com if u have pls. Sorry for my english.

**Comment by struthio** [comment]
I will add those cities in first week of december.
As for WeatherOS, currently all I can find is version 1.1 under:
http://files.domoticaforum.eu/index.php?cam=/Oregon

**Comment by AMGSoUL** [comment]
Thanks a lot! I hope this version can work on windows 7

вс, 22 нояб. 2015 г. в 18:03, struthio notifications@github.com:

**Comment by struthio** [comment]
City Saratov (woeid 2123272) should be available in Cities list in config menu.

**Comment by AMGSoUL** [comment]
Hello again, ty for adding, but I can't find in Saratov in list of Russia,
list is empty. And can you tell me what's happened with servers?

пт, 4 дек. 2015, 1:24, struthio notifications@github.com:

**Comment by struthio** [comment]
I've added new issue. Yes server is down, and because of that nothing will work on I600.

Good thing is I found 1.2 version of WeatherOS and I will try to share is as soon as connection to my server is restored.

**Comment by AMGSoUL** [comment]
Hello, i can't find Saratov (woeid 2123272) in cities list in config menu.
![saratov](https://cloud.githubusercontent.com/assets/15894103/12448805/913b031e-bf89-11e5-9f24-c02e89f5426d.PNG)

**Comment by struthio** [comment]
Sorry something wrong happened. It seems that cache was not correctly updated and list of city in Russia never got updated (although server claimed that correctly added Saratov to Russia city cache).

I cleared whole cache and reloaded it again from scratch. Now Saratov should be visible.

**Comment by wjpc** [comment]
Hello, I am a Chinese i600 user. 
Since Oregon Scientific closed the server, my i600 has become a piece of junk.
Fortunately, I find your server now. But I can not find some cities in cities list .
Can you please help me to add them into the list?
(woeid=2132613  Weitang)
(woeid=2151849  Shanghai)
Look forward to your reply.
Thank you very much.

**Comment by struthio** [comment]
Cities should be available.

**Comment by wjpc** [comment]
Yes, it works very well.
Thanks again.

**Comment by wjpc** [comment]
Hello, struthio.
I used your server to update my i600 earlier this year.
But now I find I can not set my cities in Weather OS.
I have used both Weather OS v. 1.2  and v1.1, but they all did not work properly.
The home city can be only selected from Poland, city 1 to 4 can not be selected.
Could you help me to solve this problem?
Thank you very much.
![123](https://cloud.githubusercontent.com/assets/16852460/20796262/5f2a3a4a-b810-11e6-8b47-182bd25a3251.JPG)

**Comment by struthio** [comment]
I will look into this.

**Comment by wjpc** [comment]
It is OK now.
Thanks again for your kind help.
