### ISSUE TITLE
High temperature C

### ISSUE THREAD

**Issue by AMGSoUL** [struthio/phpOregonI600#4]
Hello, thanks you for help, but day ago my station i600 show too high temperature from internet. Can you help me fix thix?
![image](https://cloud.githubusercontent.com/assets/15894103/14048611/6f76686c-f2c0-11e5-8e82-ad38ff39112b.png)

**Comment by struthio** [comment]
It seems that Yahoo started to return weather in Fahrenheit instead of Celsius.
I manually translated Fahrenheit to Celsius, so after next synchronization Your I600 should show correct values.

**Comment by AMGSoUL** [comment]
Thanks a lot for help!
