### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SanSanish** [struthio/phpOregonI600#5]
You can write the complete instructions for installing and configuring the server weather.
As "Oregon Scientific I600 - Working Again". Thank you.
I have the I300 is connected to your server, Saratov weather there.
Ask add 6310 Rostov-na-Donu Russia

**Comment by struthio** [comment]
1. Download Weather OS installer
   Windows Vista: http://files.domoticaforum.eu/uploads/Oregon/OSWeather_1.1.msi
   Windows 7: https://drive.google.com/file/d/0B4QqRbwG8YfyTmp1elEyVGt0QTg/view?usp=sharing
   http://files.domoticaforum.eu/index.php?cam=/Oregon
2. Install it normally
3. Open Weather OS Config.ini file in notepad
   Windows 32-bit: C:\Program Files\Oregon Scientific\Weather OS\Config.ini
   Windows 64-bit: C:\Program Files (x86)\Oregon Scientific\Weather OS\Config.ini
4. In opened Config.ini, change:
   {server}=www.os-weather.com
   to
   {server}=oregon.superstar.one.pl
5. Start Weather OS with administrative privileges (Right Click on WeatherOS.exe file and "Run as Administrator")
6. Configure Weather OS normally

**Comment by SanSanish** [comment]
Re: [struthio/phpOregonI600] Question (#5)

Здравствуйте, struthio.

Вы писали 12 октября 2016 г., 22:19:53:

Download Weather OS installer Windows Vista: http://files.domoticaforum.eu/uploads/Oregon/OSWeather_1.1.msi Windows 7: https://drive.google.com/file/d/0B4QqRbwG8YfyTmp1elEyVGt0QTg/view?usp=sharing http://files.domoticaforum.eu/index.php?cam=/Oregon
Install it normally
Open Weather OS Config.ini file in notepad Windows 32-bit: C:\Program Files\Oregon Scientific\Weather OS\Config.ini Windows 64-bit: C:\Program Files (x86)\Oregon Scientific\Weather OS\Config.ini
In opened Config.ini, change: {server}=www.os-weather.com to {server}=oregon.superstar.one.pl
Start Weather OS with administrative privileges (Right Click on WeatherOS.exe file and "Run as Administrator")
Configure Weather OS normally

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Спасибо за ответ. Это я все понял и сделал. У меня есть сервер который был настроен на Yhoo RSS.(http://users.skynet.be/luc.pauwels/luc/weatheros/)
Он перестал работать.Был настроен по этой инструкции. Я хотел бы получить инструкцию по настройке своего сервера на базе Ваших php скриптов.
Заранее спасибо.

Thanks for the reply. This I understood everything and did. I have a server that has been configured for Yhoo RSS. (http://users.skynet.be/luc.pauwels/luc/weatheros/)
It stopped working on this was configured for instructions. I would like to get instructions for setting up your own server on the base of your php scripts.
Thanks in advance.

## 

С уважением,
 Alexandr                          mailto:zav@spark-mail.ru

**Comment by struthio** [comment]
Well in theory, to make this code work on Your PC you need Apache (with mod_rewrite and php) installed. Then just clone this repository to some path that Apache sees as webpage.

Unfortunately on GitHub there is old version of code (which I am not sure that works 100%). A am planing to release whole code (as soon as I clean up it) but because lack of time I am just 'maintaining' script on server without time to do any major modifications.

**Comment by SanSanish** [comment]
Re: [struthio/phpOregonI600] Question (#5)

Здравствуйте, struthio.

Вы писали 19 октября 2016 г., 0:08:08:

Well in theory, to make this code work on Your PC you need Apache (with mod_rewrite and php) installed. Then just clone this repository to some path that Apache sees as webpage.
Unfortunately on GitHub there is old version of code (which I am not sure that works 100%). A am planing to release whole code (as soon as I clean up it) but because lack of time I am just 'maintaining' script on server without time to do any major modifications.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
1. Поставил Apache, включил mod_rewrite. PHP.
2. Скопировал файлы Вашего скрипта в /var/www/mds/
3. Дал разрешения.
4. Настроил :
        criptAlias /mds/ "/var/www/mds/"
        <Directory "/var/www/mds">
        AllowOverride All
        Options None
        Order allow,deny
        Allow from all
        </Directory> 
   Пытаюсь подключится - подключения нет. В чем может быть проблема ?
   Заранее спасибо.
5. Put the Apache mod_rewrite, included. PHP.
6. Copied your script files in/var/www/mds/
7. Gave permission.
8. Configured:
        criptAlias/mds/"/var/www/mds/"
        < Directory "/var/www/mds" >
        Allowoverride All
        Options None
        Order allow, deny
        Allow from all
        </Directory> 
   Try to connect-no connection. What can be problem?
   Thanks in advance.
   -- 
   С уважением,
   Alexandr                          mailto:zav@spark-mail.ru

**Comment by struthio** [comment]
What do you mean by 'no connection' ?
Can you paste your error.log from PHP/Apache ?

**Comment by SanSanish** [comment]
Weather OS Config.ini file - my server (192.168.1.37) - no connection
You can ask you for complete instructions on how to install your script as (http://users.skynet.be/luc.pauwels/luc/weatheros/), on agenda items.
Thank you.

**Comment by struthio** [comment]
I've made some changes today. Simplest way to execute this script will be through docker.
To install docker on ubuntu:
`apt install docker.io`

Then to start this script just type:
`docker run -d -p 80:80 struthio/phporegoni600`

(Port 80 must be free).
Please mind that there are some problems with yahoo and ex. geo.continets do not return data.

**Comment by SanSanish** [comment]
Большое спасибо за Вашу работу. Поставил Ваш скрипт. 
1. не происходит автозапуска сервера
2. из клиента не возможно выбрать город , страну, регион

Thank you very much for your work. Put your script. 
1. not happening server startup
2. from the client it is not possible to select a city, country, region

**Comment by SanSanish** [comment]
У меня сервер на HP Proliant 360. Docker.io не установишь.
Поставил в ручную. Из файла docker. 
Подскажите пожалуйста - как в ручную вбить свой город (в код) 
Ростов-на-Дону.
Спасибо.

I have a server on HP Proliant 360. Docker.io not ustanovish'.
Put in the manual. From the file of the docker. 
Please tell me-how to manually drive your city (in code) Rostov-na-Donu.
Thank you.

**Comment by struthio** [comment]
hi,

Sorry but I so not have much spare time to dedicate it to this project.
Most likely missing data is caused by Yahoo not replaying correctly to geo.continents request. And this data is essential to other requests.

As a workaround for this issue, It is possible to manually overwrite geo.continents response with static data. But currently I do not have much time to provide this change.

You can always use my server for updating I300/I600 station.

**Comment by SanSanish** [comment]
Re: [struthio/phpOregonI600] Question (#5)


Здравствуйте, struthio.

Вы писали 27 ноября 2016 г., 2:17:21:





hi,
Sorry but I so not have much spare time to dedicate it to this project.
Most likely missing data is caused by Yahoo not replaying correctly to geo.continents request. And this data is essential to other requests.
As a workaround for this issue, It is possible to manually overwrite geo.continents response with static data. But currently I do not have much time to provide this change.
You can always use my server for updating I300/I600 station.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



Большое СПАСИБО за Вашу работу !
Все работает, подставил в ручную свой код города в клиенте.
А с Вашего сервера можно выбрать только несколько городов и все.
Нет Выбора города. У меня так же.

Thanks a lot for your work!
Everything works, framed in hand your area code in the client.
And with your server, you can choose only a few cities and all.
No choice in the city. I have the same.

-- 
С уважением,
 Alexandr                          mailto:zav@spark-mail.ru

**Comment by struthio** [comment]
hi,

Currently Yahoo does not support old way of querying by YQL.
Because user YQL do not work, codes included in this repository will not work.

In order of making this work You will have to rewrite Yahoo class but is is currently not covered by this project.

There is another issue created for making this codes work again #6
