### ISSUE TITLE
Server do not return weather information.

### ISSUE THREAD

**Issue by struthio** [struthio/phpOregonI600#6]
Due Yahoo changing their API, I600 does not receive any weather information.

**Comment by przemerr** [comment]
Hello, Today I stumbled upon your project. I've resurrected my I600, but noticed the yahoo API issue. Are you trying to fix it? I don't want to rush you or anything, just asking if you left the project. Have a good day.

**Comment by struthio** [comment]
Yes. I will try fix it. Although it will take me about month to do so.

**Comment by struthio** [comment]
Hi,
I've just uploaded very early stage of new version. It should work now.
If You had it previously working, You will have to select cities again (since City ID have changed, because I no longer use Yahoo WOEID).

**Comment by struthio** [comment]
For new Cities or bugs please create separate tickets (one per city or bug).
