### ISSUE TITLE
New city request

### ISSUE THREAD

**Issue by przemerr** [struthio/phpOregonI600#7]
Can you add Opole, Poland, to the city list?

Thank you.

**Comment by struthio** [comment]
Please try to setup I600 station. Opole should be available now.

**Comment by przemerr** [comment]
Hello, It briefly worked (i could choose Opole from the list, but it didn't update the weather). Now, if I want to select any city, all of the select-bars are greyed out. Don't know if I made a mistake somewhere (can't trust the software) or the issue is server sided.

![image](https://cloud.githubusercontent.com/assets/25085095/22734202/2269e478-edf5-11e6-8605-63cd1e1221ce.png)

**Comment by przemerr** [comment]
Don't know if you did something or not but everything is working fine now :)

Thank you.

**Comment by struthio** [comment]
Yes. There was a bug that prevented listing of locations.
Yesterday I was able to fix this.
