### ISSUE TITLE
Max = Min

### ISSUE THREAD

**Issue by przemerr** [struthio/phpOregonI600#8]
Sometimes the maximum temperature is not shown properly. Also "full sun" icon is not shown at all.
![image](https://cloud.githubusercontent.com/assets/25085095/22823360/7f4be238-ef83-11e6-9107-e4eff2124d81.png)

using forecast.io.

**Comment by struthio** [comment]
I made some general fixes for this, can You tell what weather source You used when this bug appeared (Forecast.IO or OpenWeatherMap) ?
Can You check if this issue still exists ?

**Comment by przemerr** [comment]
Looking good, thank you, I'm using forecast.io.

**Comment by wjpc** [comment]
I have met the same problem. Weather souce is  OpenWeatherMap.
![default](https://cloud.githubusercontent.com/assets/16852460/22855210/1d2b8b3c-f0b7-11e6-9b4c-e52d952f9da7.JPG)

**Comment by struthio** [comment]
Unfortunately for OpenWeatherMap this is what I receive from provider.
For weather for days other that 'Today', temperatures
![zrzut ekranu z 2017-02-12 00-36-03](https://cloud.githubusercontent.com/assets/4520780/22858379/86219290-f0bb-11e6-8578-fd114ac7b446.png)
 are always equal.
