### ISSUE TITLE
Modify cities

### ISSUE THREAD

**Issue by wjpc** [struthio/phpOregonI600#9]
Dear struthio,
I found my cities' information from Forecast.IO and OpenWeatherMap is different from Yahoo.
I also can not get weather from Forecast.IO. 
Does it need to modify the longitute and latitude?
City 1:  Shanghai,  [31.2253,121.4889]@ Forecast.IO,   [31.2222, 121.4581]@openweathermap;
City 2:  Jiashan,  [30.85,120.9]@ Forecast.IO,   [30.8492, 120.9258]@openweathermap;

The picture is the information from the software now.
![1](https://cloud.githubusercontent.com/assets/16852460/22855384/b8d6605e-f0ba-11e6-9830-dc0a6b71d36e.JPG)

I'm sorry to give you so much trouble.
Thank you very much.

**Comment by struthio** [comment]
I will look into that.

**Comment by struthio** [comment]
Hi unfortunately OpenWeatherMap gives me some errors. Probably there is problem with OWM 2.5 API, it gives errors even when I query it manually.

I will add feature to disable Weather Provider and will disable OWM until it is fixed.

**Comment by wjpc** [comment]
I am using Forecast.IO now. 
OpenWeatherMap and Yahoo are not available for my cities.  So it is no influence for me. 
Give you so much trouble. Thank you very much!
